config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get    '/login',   to: 'welcome#index'
  post   '/login',   to: 'sessions#create'
  get '/logout',  to: 'sessions#destroy'
  get '/help', to:'welcome#help'
  get '/about', to:'welcome#about'
  get '/index', to:'welcome#index'
  get '/contact', to:'welcome#contact'
  get '/tutors', to:'welcome#tutors'
  get  '/signup',  to: 'users#new'
  post  '/signup',  to: 'users#create'
  post '/create_student_tutor', to:'users#create_student_tutor'
  get '/redirect', to: 'tutor_sessions#redirect', as: 'redirect'
  get '/callback', to: 'tutor_sessions#callback', as: 'callback'
  get '/calendars', to: 'tutor_sessions#calendars', as: 'calendars'
  get '/events/:calendar_id', to: 'tutor_sessions#events', as: 'events', calendar_id: /[^\/]+/
  post '/events/:calendar_id', to: 'tutor_sessions#new_event', as: 'new_event', calendar_id: /[^\/]+/



  resources :users do
    resources :comments
  end
  resources :tutor_sessions,          only: [:create, :destroy,:edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tutor_session.rb
class TutorSession < ApplicationRecord
  belongs_to :user
  # belongs_to :student, index: true, dependent: :destroy,
  # belongs_to :tutor, index: true, dependent: :destroy,
  default_scope -> { order(date: :asc) }
  validates :user_id, presence: true
  validates :subject, presence: true, length: { maximum: 30 }
  validates :date, presence: true
  validates :starttime, presence: true
  validates :endtime, presence: true
  validate :endtime_after_start_time
  before_save :calculate_time_duration

  def calculate_time_duration
  	self.time_duration = (self.endtime - self.starttime)/3600
  end

  def endtime_after_start_time
    if endtime < starttime
      errors.add(:endtime, "End time can't be before start time!")
    end
  end
end

app/controllers/tutor_sessions_controller.rb
class TutorSessionsController < ApplicationController
    before_action :logged_in_user, only: [:create, :destroy,:edit, :update]
    # before_save :calculate_time_duration

    def create
        @tutor_session = current_user.tutor_sessions.build(sessions_params)
        if @tutor_session.save
          flash[:success] = "Session created!"
          new_event(sessions_params)
          redirect_to current_user
        else
            redirect_to current_user
        end
    end

    def edit
        @tutor_session = current_user.tutor_sessions.find_by(params[:id])
    end

    def update
        @tutor_session = current_user.tutor_sessions.find_by(id:current_user.tutor_sessions.ids)

        if @tutor_session.update(sessions_params)
          redirect_to current_user
        else
          render 'edit'
        end
    end

    def destroy
        @tutor_session = current_user.tutor_sessions.find_by(params[:id])
        @tutor_session.destroy

        flash[:success] = "Session deleted"
        redirect_to request.referrer
    end


    def redirect
      client = Signet::OAuth2::Client.new(client_options)

      redirect_to client.authorization_uri.to_s
    end

    def callback
        client = Signet::OAuth2::Client.new(client_options)
        client.code = params[:code]

        response = client.fetch_access_token!

        session[:authorization] = response

        redirect_to calendars_url
      end

      def calendars
        client = Signet::OAuth2::Client.new(client_options)
        client.update!(session[:authorization])

        service = Google::Apis::CalendarV3::CalendarService.new
        service.authorization = client

        #cal = Google::Apis::CalendarV3::Calendar


        @calendar_list = service.list_calendar_lists

        #aacessing first google calendar using calendars
        result = service.list_calendar_lists.items[0].id
        #result = client.issuer

        link = "/events/" + result
        redirect_to link

      rescue Google::Apis::AuthorizationError
        response = client.refresh!

        session[:authorization] = session[:authorization].merge(response)

        retry
      end

    def events
       client = Signet::OAuth2::Client.new(client_options)
       client.update!(session[:authorization])

       service = Google::Apis::CalendarV3::CalendarService.new
       service.authorization = client

       @event_list = service.list_events(params[:calendar_id])
      end

     def new_event(sessions_params)
      client = Signet::OAuth2::Client.new(client_options)
      client.update!(session[:authorization])

      service = Google::Apis::CalendarV3::CalendarService.new
      service.authorization = client

      require 'date'
      Time.now.to_datetime.rfc3339
      @today = Date.today
      @subject = params[:tutor_session][:subject]
      #@start_date = params[:user][:start_date]
      #@end_date = params[:user][:end_date]
      event = Google::Apis::CalendarV3::Event.new({
        start: {

       date_time: "2018-04-06T17:00:00-07:00"


       #@date.to_datetime.rfc3339
     },
     end: {
       date_time: "2018-04-06T19:00:00-07:00"
       #@date.to_datetime.rfc3339
      },

        summary: @subject,
      })

      result = service.list_calendar_lists.items[0].id

      service.insert_event(result, event)

      end



    private
        def sessions_params
            if current_user.role == "Tutor"
                tutor_id = current_user.id
            elsif current_user.role == "Student"
                student_id = current_user.id
            end
            params.require(:tutor_session).permit(:tutor_id, :student_id,:subject,:date,:starttime,:endtime,:time_duration)
        end
        def client_options
          {
            client_id: Rails.application.secrets.google_client_id,
            client_secret: Rails.application.secrets.google_client_secret,
            authorization_uri: 'https://accounts.google.com/o/oauth2/auth',
            token_credential_uri: 'https://accounts.google.com/o/oauth2/token',
            scope: Google::Apis::CalendarV3::AUTH_CALENDAR ,
            redirect_uri: callback_url
          }
          end
end

app/helpers/tutor_sessions_helper.rb
module TutorSessionsHelper
end

app/views/tutor_sessions/_tutor_session.html.erb
<div class="card">
	<li id="tutor_session-<%= tutor_session.id %>" class="tutor_session_list">
		<div class="card-body">
		<% if @user.role == "Tutor" %>
			<% if tutor_session.student_id == nil %>
				<h4 class="subject card-title name"><%= tutor_session.subject%></h4> 
				<h5 class="card-subtitle mb-2 text-muted">with <span class="name"><%= User.find(tutor_session.user_id).firstname %></span></h5>
			<% else %>
				<h4 class="subject card-title name"><%= tutor_session.subject%></h4>
				<h5 class="name card-subtitle mb-2 text-muted"> with <span class="name"><%= User.find(tutor_session.student_id).firstname %></span></h5> 
			<% end %>
		<% end %>

		<% if @user.role == "Student" %>
			<% if tutor_session.tutor_id == nil %>
				<h4 class="subject card-title name"><%= tutor_session.subject%></h4>
				<h5 class="card-subtitle mb-2 text-muted">with <span class="name"><%= User.find(tutor_session.user_id).firstname %></span></h5>

			<% else %>
				<h4 class="subject card-title name"><%= tutor_session.subject%> </h4>
				<h5 class="card-subtitle mb-2 text-muted">with <span class="name"><%= User.find(tutor_session.tutor_id).firstname %></span></h5>
			<% end %>
		<% end %>
		<p class="date card-text"><%= tutor_session.date.strftime("%a, %B %d, %Y") %></p>
		<p class="time card-text"><%= tutor_session.starttime.time.strftime("%I:%M %p") %> - <%= tutor_session.endtime.time.strftime("%I:%M %p") %></p>
		<p class="card-text"><%= tutor_session.time_duration %> hour(s)</p>

		<% if tutor_session.tutor_id == nil %>
			<p>Session cost: <%= number_to_currency(Tutor.find(tutor_session.user_id).rate * tutor_session.time_duration) %></p> 
		<% else %>
			<p>Session cost: <%= number_to_currency(Tutor.find(tutor_session.tutor_id).rate * tutor_session.time_duration) %> </p>
		<% end %>

		<small class="card-text">Created by <span class="name"><%= User.find(tutor_session.user_id).firstname %></span> </small></br>

		<% if tutor_session.user_id == @user.id %>
		<span class="edit"><%= link_to "Edit",  edit_tutor_session_path, class: 'card-link' %></span>
		<span class="delete"><%= link_to "Delete", tutor_session_path,method: :delete, data: {title: 'Are you sure?', confirm: 'Confirm to delete this tutor session' }, class: 'card-link' %></span>
		<% end %>
		<!-- <span class="timestamp">

		  Created <%= time_ago_in_words(tutor_session.created_at) %> ago.
	</span> -->
		</div>
	</li>
</div>

app/views/tutor_sessions/calendars.html.erb
<ul>
 <% @calendar_list.items.each do |calendar| %>
   <li><%= calendar.summary %> (<%= calendar.id %>)</li>
 <% end %>
</ul>

app/views/tutor_sessions/edit.html.erb
<% provide(:title, "Edit session") %>
<%= render 'layouts/header' %>
<h2 id="page-title">Update your session</h2>

<div class="container">
  <%= form_with(model: @tutor_session) do |f| %>
    <div class="form-group">
      <%= f.label :subject %>
      <%= f.text_field :subject, class: 'form-control' %>
    </div>  
    <div class="form-group">
      <%= f.label :date %>
      <%= f.date_select :date, prompt: {day: 'Select day', month: 'Select month', year: 'Select year'}, class: 'form-control' %>
    </div> 
    <div class="form-inline">
      <%= f.label :"Start time" %>
      <%= f.time_select :starttime, {ampm: true}, class: 'form-control' %> </br>
      <%= f.label :"End time" %>
      <%= f.time_select :endtime, {ampm: true}, class: 'form-control' %>
    </div>
    <%= f.submit "Save", class: 'btn btn-primary' %> 

  <% end %>

  <button class="btn btn-primary"><%= link_to 'Back', user_path %></button>
</div>

app/views/tutor_sessions/events.html.erb
<% provide(:title, "Tutor sessions") %>
<%= render 'layouts/header' %>

<div id = "url_id"> <%= params[:calendar_id] %> </div>
<div id = "calendar_embed" > </div>

<script type='text/javascript'>

  var a = document.getElementById('url_id').innerHTML;
  var b = a.slice(1,-11);
  console.log (a);
  console.log (b);
  var c = "https://calendar.google.com/calendar/embed?src=" + b +"%40gmail.com&ctz=America%2FVancouver";
  console.log(c)
  //document.getElementById('calendar').src = c;
  var iframe = document.createElement('iframe');
  iframe.frameBorder=0;
  iframe.width="800px";
  iframe.height="600px";
  iframe.id="calendar";
  iframe.setAttribute("src", c);
  document.getElementById("calendar_embed").appendChild(iframe);

</script>