config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get    '/login',   to: 'welcome#index'
  post   '/login',   to: 'sessions#create'
  get '/logout',  to: 'sessions#destroy'
  get '/help', to:'welcome#help'
  get '/about', to:'welcome#about'
  get '/index', to:'welcome#index'
  get '/contact', to:'welcome#contact'
  get '/tutors', to:'welcome#tutors'
  get  '/signup',  to: 'users#new'
  post  '/signup',  to: 'users#create'
  post '/create_student_tutor', to:'users#create_student_tutor'
  get '/redirect', to: 'tutor_sessions#redirect', as: 'redirect'
  get '/callback', to: 'tutor_sessions#callback', as: 'callback'
  get '/calendars', to: 'tutor_sessions#calendars', as: 'calendars'
  get '/events/:calendar_id', to: 'tutor_sessions#events', as: 'events', calendar_id: /[^\/]+/
  post '/events/:calendar_id', to: 'tutor_sessions#new_event', as: 'new_event', calendar_id: /[^\/]+/



  resources :users do
    resources :comments
  end
  resources :tutor_sessions,          only: [:create, :destroy,:edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.erb
<% provide(:title, "About") %>
<%= render 'layouts/header' %>
    <h2 id="page-title">About Tutor 4 Me</h2>
    <p>Tutor 4 Me is an application that allows students and parents to seek for one of our qualified tutors, and keep track of upcoming tutor sessions. </p>

app/views/welcome/contact.html.erb
<% provide(:title, "Contact") %>
<%= render 'layouts/header' %>
    <h2 id="page-title">Contact</h2>

app/views/welcome/help.html.erb
<% provide(:title, "Help") %>
<%= render 'layouts/header' %>
    <h2 id="page-title">Help</h2>
    <h3>For clients: </h3>
    <p>If you don't have an account yet, please <%= link_to "create an account", signup_path %> first.</p>
  </body>
</html>

app/views/welcome/index.html.erb
<% provide(:title, "Log in") %>
<%= render 'layouts/header' %>
<h2 id="page-title">User Login</h2>
<div class="container">
<% if logged_in? %>
  <p>You are already logged in. If you'd like to log in to another account, please log out first.</p>
<% else %>
  <%= form_with scope: :user, url:login_path, local: true do |form| %>
  <div class="form-group">
    <%= form.label :"email address" %><br>
    <%= form.text_field :username, class: 'form-control' %>
  </div>
 
  <div class="form-group">
    <%= form.label :password %><br>
    <%= form.password_field :password, class: 'form-control' %>
  </div>

  <%= form.submit "Log in", class: 'btn btn-primary'%>

  <% end %>
 </div>
<% end %>

app/views/welcome/tutors.html.erb
<% provide(:title, "Tutors") %>
<%= render 'layouts/header' %>
<h2 id="page-title">Our Tutors</h2>

<% User.where(role: "Tutor").each do |user| %>
	<div class="container">
	<h3 class="name"><%= user.firstname + " " + user.lastname%></h3>
		<p><strong>Location: </strong><span class="name"><%= user.location %></span> </p>
		<p><strong>Education level: </strong><%= user.education_level %></p>
	 	<% Tutor.where(user_id: user.id).each do |tutor| %>
		 	<p><strong>School: </strong><span class="name"><%= tutor.school %></span>  </p>
		 	<p><strong>Rate: </strong><%= number_to_currency(tutor.rate) %>/hr</p>
		 	<p><strong>Bio: </strong><%= tutor.bio %></p>
		  <p><strong>Subjects: </strong><span class="name"><%= tutor.subjects %></span> </p>

      <p><strong>Comments from the students:</strong></p>
        <% user.comments.each do |comment| %>
          <p>
            <%= comment.body %>
          </p>
        <% end %>

		    <% if current_user.role == "Student" %>
				<% if current_user.students.find(current_user.id).tutors.exists?(tutor.user_id) %>
					<p>You have already added this tutor.</p>

					 <p><strong>Add a comment:</strong></p>
			        <%= form_with(model: [ user, user.comments.build ], local: true, html: {class: "small-form"}) do |form| %>
				        <div class="form-group">
				            <%= form.text_field :body, class: 'form-control' %>
				        </div>

				        <div class="form-group">
				            <%= form.submit "Add comment", class: 'btn btn-primary' %>
				        </div>

			        <% end %>

				<% else %>

					<%= link_to 'Add tutor', create_student_tutor_path(:tutor_id => tutor.user_id, :student_id => current_user.id), :method => :post, class: 'btn btn-primary', data: {title: 'Are You Sure?',confirm: 'Confirm to add this tutor', commit: 'Confirm'} %>

				<% end %>

			<% end %>
	 	<% end %>

	</div>
	</br>
<% end %>