config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get    '/login',   to: 'welcome#index'
  post   '/login',   to: 'sessions#create'
  get '/logout',  to: 'sessions#destroy'
  get '/help', to:'welcome#help'
  get '/about', to:'welcome#about'
  get '/index', to:'welcome#index'
  get '/contact', to:'welcome#contact'
  get '/tutors', to:'welcome#tutors'
  get  '/signup',  to: 'users#new'
  post  '/signup',  to: 'users#create'
  post '/create_student_tutor', to:'users#create_student_tutor'
  get '/redirect', to: 'tutor_sessions#redirect', as: 'redirect'
  get '/callback', to: 'tutor_sessions#callback', as: 'callback'
  get '/calendars', to: 'tutor_sessions#calendars', as: 'calendars'
  get '/events/:calendar_id', to: 'tutor_sessions#events', as: 'events', calendar_id: /[^\/]+/
  post '/events/:calendar_id', to: 'tutor_sessions#new_event', as: 'new_event', calendar_id: /[^\/]+/



  resources :users do
    resources :comments
  end
  resources :tutor_sessions,          only: [:create, :destroy,:edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<header class="navbar"> 
	<nav class="navbar-dark bg-primary">
		<h1 id="logo">Tutor 4 Me</h1>
		<ul class="nav">	 
		  <% if logged_in? %>
		  	<li class="nav"><%= link_to "Log Out",  logout_path %></li>
		    <li class="nav"><%= link_to "Dashboard",  user_path(:id => @current_user.id) %></li>
		    <li class="nav"><%= link_to "Our Tutors",  tutors_path %></li>

		  <% else %>
		    <li class="nav"><%= link_to "Log In",   root_path %></li>
		  	<li class="nav"><%= link_to "Sign up", signup_path %></li>
		  <% end %>
		  <!-- <li class="nav"><%= link_to "Contact", contact_path %></li>
		  <li class="nav"><%= link_to "About", about_path %></li>
		  <li class="nav"><%= link_to "Help",   help_path %></li> -->
		</ul>
	</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TutorApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	
    <%= yield %>
    <div class="alert">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
    </div>
     <% end %>

    
     <!--  <%= debug(params) if Rails.env.development? %> -->
    </div>

  </body>
</html>